"""as

Revision ID: 5955050ea67f
Revises: 99f6bc116570
Create Date: 2024-12-23 22:52:43.560228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5955050ea67f'
down_revision = '99f6bc116570'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
