"""wdwd

Revision ID: 7e07335db5b1
Revises: 5955050ea67f
Create Date: 2024-12-23 23:17:25.152246

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e07335db5b1'
down_revision = '5955050ea67f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
